# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificationAuthority', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sslTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Template Name')),
                ('nsCertType', models.CharField(max_length=255, verbose_name='Cert Type')),
                ('nsComment', models.CharField(max_length=255, verbose_name='Comment Cert')),
                ('cert_usage', models.CharField(blank=True, max_length=1024, null=True)),
                ('cert_usage_ext', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
