# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login_name', models.CharField(max_length=15, unique=True, verbose_name='user login')),
                ('first_name', models.CharField(max_length=32, verbose_name='First Name User')),
                ('midle_name', models.CharField(max_length=32, verbose_name='Midle Name User')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last Name User')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('departament', models.CharField(max_length=32, verbose_name='Organizational Unit Name (eg, section)')),
                ('organisation', models.CharField(max_length=32, verbose_name='Organization Name (eg, company)')),
                ('city', models.CharField(max_length=32, verbose_name='Locality Name (eg, city)')),
                ('state', models.CharField(max_length=16, verbose_name='State or Province Name (full name)')),
                ('country', models.CharField(max_length=2, verbose_name='Country Name (2 letter code)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
