# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=models.CharField(choices=[('RU', 'Russian'), ('UK', 'GB Great Britain'), ('US', 'United States of America')], default='RU', max_length=2, verbose_name='Country Name (2 letter code)'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='departament',
            field=models.CharField(max_length=64, verbose_name='Organizational Unit Name (eg, section)'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='First Name User'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='midle_name',
            field=models.CharField(max_length=64, verbose_name='Midle Name User'),
        ),
    ]
