# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20160505_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(default='Tomsk city', max_length=64, verbose_name='Locality Name (eg, city)'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=models.CharField(choices=[('RU', 'Russian'), ('UK', 'GB Great Britain'), ('US', 'United States of America')], default='RU', max_length=2, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=64, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='login_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='user login'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='organisation',
            field=models.CharField(default='Consultant ltd.', max_length=64, verbose_name='Organization Name (eg, company)'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='state',
            field=models.CharField(default='70 Tomsk region', max_length=64, verbose_name='State or Province Name (full name)'),
        ),
    ]
